server:
  port: 6092
  servlet:    context-path: /
    
#DataSource
spring:  datasource:     type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.152.1:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
#mybatis-plus
mybatis-plus:  mapper-locations: classpath:/mapper/*.xml
  #返回类的包名路径
  type-aliases-package: com.xq.pojo
  configuration:    map-underscore-to-camel-case: true
    
#dubbo
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: provider-user
  registry:
    address: zookeeper://192.168.152.130:2181
  protocol:
    name: dubbo
    port: 20881
    
#引入logger日志
logging:
  level:
    com.xq: info